CREATE TABLE FOURNISSEUR(
FOURNISSUER_ID INT PRIMARY KEY NOT NULL,
SOURCE_ID VARCHAR(10) FOREIGN KEY REFERENCES CONTRIBUALBLE(NIF),
FOURNISSEUR VARCHAR(10) FOREIGN KEY REFERENCES CONTRIBUALBLE(NIF),
PERIODE DATE,
MONTANT_TTC FLOAT,
MONTANT_THT FLOAT,
MONTANT_TVA FLOAT,
)

CREATE TABLE CLIENT(
FOURNISSUER_ID INT PRIMARY KEY NOT NULL,
SOURCE_ID VARCHAR(10) FOREIGN KEY REFERENCES CONTRIBUALBLE(NIF),
FOURNISSEUR VARCHAR(10) FOREIGN KEY REFERENCES CONTRIBUALBLE(NIF),
PERIODE DATE,
MONTANT_TTC FLOAT,
MONTANT_THT FLOAT,
MONTANT_TVA FLOAT,
RISTOURNE FLOAT,
PEREQUATIONS FLOAT
)

CREATE TABLE SYDONIA(
SYDONIA_ID INT PRIMARY KEY NOT NULL,
CONTRIBUALBLE_ID VARCHAR(10) FOREIGN KEY REFERENCES CONTRIBUALBLE(NIF),
NUMERO_ENREGISTREMENT VARCHAR(20),
REGIME VARCHAR(250),
TRANSITAIRE VARCHAR(250),
TVA_AU_CORDON_DOUANIERE FLOAT,
RETENU_BIC FLOAT,
DROIT_LIQUIDE VARCHAR(250),
VALEUR_CAF FLOAT,
PAYS_PROVENANCE VARCHAR(50),
PRODUITS VARCHAR(250),
DESIGNATION_MARCHANDISES VARCHAR(250),
NUMERO_QUITTANCE VARCHAR(10),
)


CREATE TABLE AVIS_PASSAGE(
AVIS_PASSAGE_ID INT PRIMARY KEY NOT NULL,
RESPONSABLE VARCHAR(100),
SOURCE_ID VARCHAR(10) FOREIGN KEY REFERENCES CONTRIBUALBLE(NIF),
DATE_PASSAGE DATE,
DATE_COLLECTE DATE,
STATUT VARCHAR(3),
PERIODE VARCHAR(4),
)