INSERT INTO SERVICE_GESTIION ( SIGLE, DESCRPTION) VALUES(
'DI SUD-EST','DI SUD-EST'),
('DI SUD-OUEST','DI SUD-OUEST'),
('DME','DIRECTION MOYENNE ENTREPRISE'),
('DGE','DIRECTION GRANDE ENTREPRISE')

INSERT INTO DOMAINE_ACTIVITE (DESCRIPTION) VALUES 
('INDUSTRIE'),('INDUSTRIE PLASTIQUE'),
('INDUSTRIE LAITIERE'),
('INDUSTRIE AGRO ALIMENTAIRE'),
('PRODUCTION DEAU'),
('JEUX DE HASARD'),
('CONSTRUCTION METALLIQUE'),
('QUINCAILLERIE'),
('PNEUMATIQUE'),


SELECT * FROM SERVICE_GESTIION;

SELECT * FROM DOMAINE_ACTIVITE;

