INSERT INTO CONTRIBUALBLE
(NIF,
RAISON_SOCIALE,
ADRESSE,
ACTIVITE,
TELEPHONE,
ANCIEN_NIF,
DATE_CREATION,
DOMAINE_ACTIVITE_ID,
SERVICE_GESTIION_ID) 
VALUES
('1000174537',
'AFRIC INDUSTRY',
'S',
'Se',
'22710550',
'',
'23-06-2021',
2,
4)

INSERT INTO FOURNISSEUR  VALUES ('1000174537', '1000174537', '2020', 45554555, 56655, 4566777)

SELECT * FROM CONTRIBUALBLE;

SELECT * FROM SERVICE_GESTIION;

SELECT * FROM DOMAINE_ACTIVITE;

SELECT NIF, RAISON_SOCIALE, ADRESSE, ACTIVITE, TELEPHONE, ANCIEN_NIF, DATE_CREATION, SIGLE, DESCRIPTION FROM CONTRIBUALBLE, SERVICE_GESTIION, DOMAINE_ACTIVITE 
WHERE CONTRIBUALBLE.DOMAINE_ACTIVITE_ID =  DOMAINE_ACTIVITE.ID_ACTIVITE
AND CONTRIBUALBLE.SERVICE_GESTIION_ID = SERVICE_GESTIION.ID_SERVICE